import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import {Card, CardBody, CardHeader, CardFooter, Text, Image, Stack, Box, Flex, Container, Tag } from '@chakra-ui/react'
import {useState, useEffect} from 'react'
import { imageConfigDefault } from 'next/dist/shared/lib/image-config'
import {ImageCard} from '@/components/ImageCard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [images, setImages] = useState([]);
  const [isLoading, setIsLoading] = useState(true);
  const [term, setTerm] = useState('');
  const apiKey = '33214573-526af4a4f768e486bd33d14f0'

  useEffect(()=>{
    fetch(`https://pixabay.com/api/?key=${apiKey}&q=${term}&image_type=photo&pretty=true`)
    .then((res)=> res.json())
    .then((data)=>{
      setImages(data.hits)
      setIsLoading(false)
    })
  }, [])
  if(isLoading) return <p>Loading...</p>
  if(!images) return <p>No Image Available</p>
  return (
    <>
      <Head>
        <title>Image Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex p='16px' pb='30px' wrap='wrap' justify='space-between'>
          {
            images.map((img)=>{
             return <ImageCard key={img.id} img={img} />
            })
          }
          
        </Flex>
        
      </main>
    </>
  )
}
